### ISSUE TITLE
Don't know how to build task 'jumpup:coverage_verify'

### ISSUE THREAD

**Issue by rafaelp** [Helabs/jumpup#68]
Coverage report generated for RSpec to /Users/rafael/Projects/bole.to/coverage. 238 / 238 LOC (100.0%) covered.
--------------------------------------------------------------------------------
--> Executing jumpup:coverage_verify...
rake aborted!
Don't know how to build task 'jumpup:coverage_verify'
/Users/rafael/.rbenv/versions/2.2.0/gemsets/bole.to/gems/jumpup-0.0.8/lib/jumpup.rb:40:in `block (2 levels) in invoke_tasks'
/Users/rafael/.rbenv/versions/2.2.0/gemsets/bole.to/gems/jumpup-0.0.8/lib/jumpup/ui.rb:10:in `header'
/Users/rafael/.rbenv/versions/2.2.0/gemsets/bole.to/gems/jumpup-0.0.8/lib/jumpup.rb:39:in `block in invoke_tasks'
/Users/rafael/.rbenv/versions/2.2.0/gemsets/bole.to/gems/jumpup-0.0.8/lib/jumpup.rb:37:in `each'
/Users/rafael/.rbenv/versions/2.2.0/gemsets/bole.to/gems/jumpup-0.0.8/lib/jumpup.rb:37:in `invoke_tasks'
/Users/rafael/.rbenv/versions/2.2.0/gemsets/bole.to/gems/jumpup-0.0.8/lib/jumpup.rb:27:in `perform_integration'
/Users/rafael/.rbenv/versions/2.2.0/gemsets/bole.to/gems/jumpup-0.0.8/lib/tasks/integrate.rake:61:in `block in <top (required)>'
Tasks: TOP => integrate
(See full trace by running task with --trace)

**Comment by thiagogabriel** [comment]
This task was removed on jumpup `0.0.6`. 
Now you have to configure spec_helper.rb to verify the coverage: https://github.com/Helabs/jumpup#protip-using-simplecov

**Comment by rafaelp** [comment]
:+1: I didn't realize it. Thanks.
